version: "3.7"
services:
    # imagem micro 01
    service_shorts:
        build:
            args:
                user: luanramos
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - service_shorts_network

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8000:80
            - 443:443
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - service_shorts_network

    # mysql micro 01
    db_service_shorts:
        image: mysql:oracle
        restart: unless-stopped
        expose:
            - 3306
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        volumes:
            - /var/lib/mysql
        ports:
            - 3308:3306
        networks:
            - service_shorts_network

    #redis
    redis:
        image: redis:latest
        networks:
            - service_shorts_network

networks:
    service_shorts_network:
        driver: bridge
